import { Link } from 'react-router-dom';
import './ChronicleVerify.css';
import AppHeader from '../../components/AppHeader.jsx';

const HASH_MATCHES = true;
const FACTS = [
  { label: 'Reference Number', value: 'AXC-2026-088341' },
  { label: 'Certified', value: '2026-08-01 09:42 UTC' },
  { label: 'Version', value: '1.0' },
  { label: 'Trading Session', value: 'TSN-2026-3115' },
  { label: 'Trading Format', value: 'Easy Auction' },
];
const MEDIA = [
  { filename: 'compressor_front.jpg', primaryTag: ' (primary)' },
  { filename: 'compressor_nameplate.jpg', primaryTag: '' },
  { filename: 'inspection_report.pdf', primaryTag: '' },
];
const TIMELINE = [
  { at: '2026-07-28 11:02:14', type: 'Lot approved by TSX Master' },
  { at: '2026-07-29 09:15:41', type: 'Trading Session opened' },
  { at: '2026-07-31 18:00:00', type: 'Bidding closed — H1 recorded' },
  { at: '2026-08-01 09:40:22', type: 'Settlement completed' },
];
const CHAIN_HASH = '9f3a7c2e18d0b4f1';

export default function ChronicleVerify() {
  return (
    <div className="cv-page">
      <AppHeader variant="light" contextLabel="Chronicle Verification" />
      <main className="cv-main">
        <h1 className="cv-title">Chronicle Verification</h1>
        <p className="cv-intro-note">This page requires no login — it's reachable only with the exact token from the QR code or verification link on the certified PDF.</p>
        <p className="cv-body-text">This AX Certified Proceedings has been automatically generated by the ADWITIX Platform based on the information, activities, approvals and records captured during the lifecycle of the event. It presents a structured summary of the proceedings together with the associated commercial outcome, compliance status and supporting records. The report forms part of the official digital record maintained for this event.</p>

        <div className="cv-verify-box" style={{ background: HASH_MATCHES ? 'var(--color-success-bg)' : 'var(--color-danger-bg)', borderColor: HASH_MATCHES ? '#CBE0D1' : '#F2CFC6' }}>
          <p style={{ color: HASH_MATCHES ? 'var(--color-success)' : 'var(--color-danger)' }}>{HASH_MATCHES ? "✓ Digital Verification: this record's content hash matches what was certified at generation. Not altered." : '⚠ Digital Verification FAILED: this record\'s content does not match its certified hash.'}</p>
        </div>

        <div className="cv-facts-card">
          {FACTS.map((f) => <div key={f.label} className="cv-fact-row"><span className="cv-fact-label">{f.label}</span><span className="cv-fact-value">{f.value}</span></div>)}
        </div>

        <Link to="/ax-chronicle" className="cv-download-btn">Download Certified PDF →</Link>

        <h3 className="cv-h3">Supporting Evidence</h3>
        <div className="cv-list-card">
          {MEDIA.map((m) => <div key={m.filename} className="cv-list-row"><a href="#">{m.filename}</a>{m.primaryTag}</div>)}
        </div>

        <h3 className="cv-h3">Audit-Trail Excerpt</h3>
        <div className="cv-list-card" style={{ marginBottom: 16 }}>
          {TIMELINE.map((ev, i) => <div key={i} className="cv-list-row cv-list-row--muted"><span className="cv-mono">{ev.at}</span> — {ev.type}</div>)}
        </div>
        <p className="cv-chain-note">Chain reference: {CHAIN_HASH}… — cross-checkable against the platform's own digital repository.</p>

        <h3 className="cv-h3">Record Integrity Statement</h3>
        <p className="cv-faint-p">This report represents a factual summary of the recorded proceedings and does not alter, replace or supersede the underlying digital records. The complete chronology of events, supporting documents, media, approvals and transaction history continue to remain available within the authorised digital repository for verification, audit and future reference in accordance with applicable organisational policies and data retention requirements.</p>

        <h3 className="cv-h3">Closing Statement &amp; Disclaimer</h3>
        <p className="cv-faint-p">This report has been generated from information available within the ADWITIX Platform as on the date and time of certification. It is intended to facilitate operational review, management reporting and institutional record keeping. Any subsequent activity or authorised update after the time of generation shall form part of a later version of the proceedings.</p>

        <p className="cv-domain">www.AdwitiX.com</p>
      </main>
    </div>
  );
}
