// Single source of truth for header navigation. Every converted route appears
// in exactly one group so the shared header can reach the whole app.
export const NAV_GROUPS = [
  {
    label: 'Marketplace',
    to: '/marketplace',
    items: [
      { label: 'Browse Marketplace', to: '/marketplace' },
      { label: 'Lot Detail', to: '/lot-detail' },
      { label: 'Bidding Room', to: '/bidding-room' },
      { label: 'Saved Searches', to: '/saved-searches' },
      { label: 'TradeSphereX Directory', to: '/tenant-directory' },
      { label: 'Pricing', to: '/pricing' },
    ],
  },
  {
    label: 'Sell',
    to: '/apply-to-sell',
    items: [
      { label: 'Apply to Sell', to: '/apply-to-sell' },
      { label: 'Create a Lot', to: '/create-lot' },
      { label: 'Market Maker Dashboard', to: '/seller/dashboard' },
      { label: 'Lot Directory', to: '/lot-directory' },
      { label: 'Lot Approval', to: '/lot-approval' },
      { label: 'Lot Reach & Interest', to: '/lot-reach-and-interest' },
      { label: 'Lot Chronicle', to: '/lot-chronicle' },
      { label: 'Defect Disclosure', to: '/defect-disclosure' },
    ],
  },
  {
    label: 'Account',
    to: '/profile',
    items: [
      { label: 'Profile', to: '/profile' },
      { label: 'Trader Dashboard', to: '/buyer/dashboard' },
      { label: 'Preferences', to: '/preferences' },
      { label: 'Star Ratings', to: '/star-ratings' },
      { label: 'Rating History', to: '/rating-history' },
      { label: 'Payout Bank', to: '/payout-bank' },
      { label: 'Change mPIN', to: '/change-mpin' },
      { label: 'Activity Log', to: '/activity-log' },
      { label: 'KYC Verification', to: '/kyc' },
      { label: 'Delete Account', to: '/delete-account' },
    ],
  },
  {
    label: 'Settlement',
    to: '/settlement',
    items: [
      { label: 'Settlement', to: '/settlement' },
      { label: 'Dispute Center', to: '/dispute-center' },
      { label: 'Dispute Resolution Process', to: '/dispute-resolution-process' },
      { label: 'Chargeback Handling', to: '/chargeback-handling' },
      { label: 'EMD Consent', to: '/emd-consent' },
      { label: 'Payout Reviews', to: '/payout-reviews' },
      { label: 'Rating Reviews', to: '/rating-reviews' },
      { label: 'Invoices', to: '/invoices' },
    ],
  },
  {
    label: 'Tender',
    to: '/tender-concierge-console',
    items: [
      { label: 'Concierge Console', to: '/tender-concierge-console' },
      { label: 'Eligibility', to: '/tender-eligibility' },
      { label: 'Auction Report', to: '/tender-auction-report' },
      { label: 'Stakeholder View', to: '/tender-stakeholder-view' },
    ],
  },
  {
    label: 'Oversight',
    to: '/custodian/dashboard',
    items: [
      { label: 'Custodian Dashboard', to: '/custodian/dashboard' },
      { label: 'Tenant Admin Dashboard', to: '/tenant-admin/dashboard' },
      { label: 'Alerts', to: '/alerts' },
      { label: 'AML Monitoring', to: '/aml-monitoring' },
      { label: 'KYC Queue', to: '/kyc-queue' },
      { label: 'Media Waivers', to: '/media-waivers' },
      { label: 'Rules & Specifications', to: '/rules-and-specifications' },
      { label: 'Whitelist TradeSphereX', to: '/whitelist-tenant' },
      { label: 'Delist Market Maker', to: '/delist-market-maker' },
      { label: 'User Directory', to: '/user-directory' },
      { label: 'User Detail', to: '/user-detail' },
      { label: 'Trading Session Directory', to: '/trading-session-directory' },
    ],
  },
  {
    label: 'Records',
    to: '/audit-ledger',
    items: [
      { label: 'Audit Ledger', to: '/audit-ledger' },
      { label: 'Audit Chain Verify', to: '/audit-chain-verify' },
      { label: 'Consent Audit', to: '/consent-audit' },
      { label: 'Statutory Export', to: '/statutory-export' },
      { label: 'AX Chronicle', to: '/ax-chronicle' },
      { label: 'Chronicle Verify', to: '/chronicle-verify' },
      { label: 'Custodian Credential Setup', to: '/custodian-credential-setup' },
    ],
  },
  {
    label: 'Trust',
    to: '/trust-and-support',
    items: [
      { label: 'Trust & Support', to: '/trust-and-support' },
      { label: 'FAQ', to: '/faq' },
      { label: 'Security & Trust', to: '/security-and-trust' },
      { label: "Do's and Don'ts", to: '/dos-and-donts' },
      { label: 'Terminology', to: '/terminology' },
      { label: 'Terms of Usage', to: '/terms-of-usage' },
      { label: 'Privacy Policy', to: '/privacy-policy' },
      { label: 'Terms & Privacy', to: '/terms-and-privacy' },
      { label: 'Cookie Policy', to: '/cookie-policy' },
      { label: 'Refund & Cancellation', to: '/refund-and-cancellation-policy' },
      { label: 'Grievance Redressal', to: '/grievance-redressal-policy' },
    ],
  },
];
